import type { Meta, StoryObj } from '@storybook/react-vite'

import { DesignTokens } from './DesignTokens'

const meta: Meta<typeof DesignTokens> = {
  title: 'Foundations/Design Tokens',
  component: DesignTokens,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'Live values read from `src/styles/tokens.css`. Once the Figma Variables export lands, this file is generated by `pnpm design:tokens` — see `docs/DESIGN_SYSTEM.md` and `docs/decisions/ADR-010-design-system-tooling.md`.',
      },
    },
  },
}

export default meta

type Story = StoryObj<typeof DesignTokens>

export const Tokens: Story = {}
